### ISSUE TITLE
MidiGate example doesn't build

### ISSUE THREAD

**Issue by Jikstra** [RustAudio/rust-lv2#102]
```
    Checking midigate v0.1.0 (/home/kerle/Coding/serial2midi-rs/midigate)
error[E0061]: this function takes 2 arguments but 1 argument was supplied
  --> midigate/src/lib.rs:80:14
   |
80 |             .read(self.urids.atom.sequence)
   |              ^^^^ ------------------------ supplied 1 argument
   |              |
   |              expected 2 arguments
   |
note: associated function defined here
  --> /home/kerle/.cargo/registry/src/github.com-1ecc6299db9ec823/lv2-atom-2.0.0/src/port.rs:50:12
   |
50 |     pub fn read<'b, A: crate::Atom<'a, 'b>>(
   |            ^^^^

For more information about this error, try `rustc --explain E0061`.
error: could not compile `midigate` due to previous error
```

Not really sure why it doesn't compile, I also tried passing () as a second argument as recommended in the read docs but also doesn't compile. Any ideas?

**Comment by derivator** [comment]
I ran into the same issue. 44aac00 changed the definition of `read`, so if you get the example from the latest commit, it won't compile with `lv2 = "0.6.0"`. You have to either [get the example from the 0.6.0 commit](https://github.com/RustAudio/rust-lv2/blob/c93bfe859a849c5189a27c62c659bd3b724a39b6/docs/midigate/src/lib.rs) or change your lv2 dependency to the latest git version. Since that still depends on the released versions of sub-packages, you probably have to deal with [overriding dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html).

**Comment by prokopyl** [comment]
Indeed, the version in the `develop` branch is not yet released, and has many breaking changes compared to the `0.6.0` version that is released on crates.io. Apologies for the confusion, I'll probably make the docs/readme/something clearer about that.

As @derivator mentioned you should probably stick to `0.6.0` until I release the next version (which I expect to be able to do soon after the holiday season), and only try out the latest git version on the `develop` branch if you enjoy sitting on the bleeding-edge. :slightly_smiling_face:
